language: scala
scala:
  - 2.12.4
sbt_args: -no-colors
dist: trusty
env:
  - SUBPROJECT=rosette
  - SUBPROJECT=core
script:
  - ./scripts/build-subprojects.sh
sudo: required
install:
  - ./scripts/install_secp.sh
  - ./scripts/install_sodium.sh
  - ./scripts/install.sh
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
notifications:
  email:
    recipients:
      - rchain-makers@pyrofex.net
    on_success: never
    on_failure: always
addons:
    apt:
        sources:
            - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
        packages:
            - sbt
            - jflex
            - haskell-platform
            - rpm
            - fakeroot

after_success:
  - "./scripts/create-artifacts.sh"

deploy:
  provider: releases
  api_key:
    secure: paewS1kvI+zK3ajfcVQmDthGcQe4j8nT+q7zdcz0Q835JXxrkoFdFksgkGVZVkNYg8wCZOc1QZz3jBM9GAHmedHqbbMQdc+dmijA0pbjU88CzcTo8PAKS52dpgStvLcLicAJ7v1Vwx6DAzkeB+WChSQhKxc00h7gFj8kh1VEBPnpsWIBPPTXGRujVX/zQoiq6oPDZwJFDOIB4hSpkNCxqsTBjT3CdeCVekUaKPVJQ88MiUDrwi30GMjv0gB1xCTSh3Fl64Rk4a7z7adK3QjRWrEmLh6hqANTt5gWrXDgwevcL0LDdFsSTsxalpuZPXhfWqwA2d+5YXNBMNkqvUFN0v8ZEoNHZl+vXvccA+au5hSBHyL4DI085llTsSWBoI8sZ/uB9WfSkdZPKV9RH4DoGuaGAlphtA4aiDO3h8PTv/uL0ei/rcBiUI7V6ZH2c+gKrggIMKHFeGeLhIOTZGylAScvNO4zB7ITbN6lF/VBlxsaOsaRnbq3WH2JFJuNAnmfv8M6ZaVhdcegT6UWWVKaWod2UksirotUuchjT1GLRtZmXSgphW2EEMsnkN4GHVqnCwnqyCKqR+SOzo3NNPESsUveCyhxY827l/ghC06Tk2K/ckZaSyP6y0Eb/m0m9W6iZt09msjoMPE296tRivdg7seAHNfj4iD18v+LLWVA3y8=
  file_glob: true
  file:
    - "node/target/*.deb"
    - "node/target/rpm/RPMS/noarch/*.rpm"
  on:
    tags: true
    branch: master
