name: Scala CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14.0.2
      uses: actions/setup-java@v1
      with:
        java-version: 14.0.2
    - name: Run tests
      run: sbt test
